FROM node:24-alpine

# https://github.com/Yelp/dumb-init
# ADD --chmod=755 https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64 /usr/bin/dumb-init
RUN apk add --no-cache dumb-init

USER node
WORKDIR /app

# node -e "require('https').get('https://example.com', v => console.log('OK', v.statusCode)).on('error', e => console.error(e))"
ENV LISTEN=0.0.0.0 \
    PORT=3000 \
    NAVPLACE_LOGGER=stdout \
    NODE_OPTIONS=--use-openssl-ca

# Leverage Docker's cache system.
# package.json will be changed less often than other files, so copy it first
# and install all dependencies.
COPY --chown=node:node package*.json .
RUN npm install

COPY --chown=node:node . .

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["npm", "run", "watch"]
