services:

  authwall:
    image: vbarbarosh/authwall
    restart: unless-stopped
    environment:
      AUTHWALL_SEED: foo:foo;bar:bar
      AUTHWALL_LOGGER: stdout
      AUTHWALL_PUBLIC_URL: http://127.0.0.1:3000
      AUTHWALL_UPSTREAM_URL: http://navplace:3000
      AUTHWALL_PUBLIC_PATHS: /favicon.ico,/robots.txt,/lib/*,/designs/*
      AUTHWALL_OPTIONAL_AUTH_PATHS: /,/index.html
      AUTHWALL_DB: mysql://authwall:authwall@mysql/authwall
      AUTHWALL_PERSONAL_ACCESS_TOKENS: true
      AUTHWALL_WEBSOCKETS: true
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4.8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/001-init.sql:ro

  navplace:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      NAVPLACE_DB: mysql://navplace:navplace@mysql/navplace
    volumes:
      - ./config:/app/config
      - ./db:/app/db
      - ./lib:/app/lib
      - ./src:/app/src
      - ./www:/app/www
    depends_on:
      - mysql

  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - 8080:8080
    depends_on:
      - mysql
