CREATE DATABASE IF NOT EXISTS authwall CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS navplace CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'authwall'@'%' IDENTIFIED BY 'authwall';
CREATE USER IF NOT EXISTS 'navplace'@'%' IDENTIFIED BY 'navplace';

GRANT ALL PRIVILEGES ON authwall.* TO 'authwall'@'%';
GRANT ALL PRIVILEGES ON navplace.* TO 'navplace'@'%';

FLUSH PRIVILEGES;
